version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-hackathon
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped

  backend:
    build: .
    container_name: flask-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - DEBUG=True
    depends_on:
      - qdrant
    volumes:
      - ./uploads:/app/uploads
      - ./static/processed:/app/static/processed
    restart: unless-stopped

volumes:
  qdrant-data:

